### ISSUE TITLE
Uncaught TypeError: Cannot read property 'scrollHeight' of undefined

### ISSUE THREAD

**Issue by raptium** [Arcath/jekyll-atom#17]
1. Create a static page, eg. `about.md`
2. Enter something
```
---
layout: page
title: 买买买
---

买买买，嗯，买……不起
```
3. Press `Ctrl+S` to save

**Atom Version**: 0.184.0
**System**: Microsoft Windows 7 Professional 
**Thrown From**: [jekyll](https://github.com/arcath/jekyll-atom) package, v0.4.3

### Stack Trace

Uncaught TypeError: Cannot read property 'scrollHeight' of undefined

```
At C:\Users\Guan Hao\.atom\packages\jekyll\lib\manage-view.coffee:82

TypeError: Cannot read property 'scrollHeight' of undefined
  at C:\Users\Guan Hao\.atom\packages\jekyll\lib\manage-view.coffee:82:59
  at Emitter.module.exports.Emitter.emit (C:\Users\Guan Hao\AppData\Local\atom\app-0.184.0\resources\app\node_modules\event-kit\lib\emitter.js:82:11)
  at Socket.<anonymous> (C:\Users\Guan Hao\.atom\packages\jekyll\lib\server.coffee:64:30)
  at Socket.emit (events.js:116:17)
  at readableAddChunk (_stream_readable.js:164:16)
  at Socket.Readable.push (_stream_readable.js:127:10)
  at Pipe.onread (net.js:530:20)

```

### Commands

```
     -1:57.5 core:confirm (atom-text-editor.editor.mini)
  2x -1:51.3 editor:newline (atom-text-editor.editor.is-focused)
  2x -1:48.3 core:save (atom-text-editor.editor.is-focused)
     -1:10.2 editor:newline (atom-text-editor.editor.is-focused)
     -1:08.6 core:save (atom-text-editor.editor.is-focused)
     -1:02.1 editor:newline (atom-text-editor.editor.is-focused)
  2x -1:00.9 core:backspace (atom-text-editor.editor.is-focused)
     -0:58.0 core:save (atom-text-editor.editor.is-focused)
  3x -0:35.9 core:backspace (atom-text-editor.editor.is-focused)
     -0:30.9 core:save (atom-text-editor.editor.is-focused)
  4x -0:28.8 core:backspace (atom-text-editor.editor.is-focused)
     -0:27.8 editor:newline (atom-text-editor.editor.is-focused)
 10x -0:15.5 core:backspace (atom-text-editor.editor.is-focused)
     -0:07.3 core:save (atom-text-editor.editor.is-focused)
  2x -0:06.9 editor:newline (atom-text-editor.editor.is-focused)
     -0:05.1 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {},
  "jekyll": {
    "jekyllBinary": "D:\\Dev\\Ruby200-x64\\bin\\jekyll.bat"
  }
}
```

### Installed Packages

```coffee
# User
jekyll, v0.4.3

# Dev
No dev packages
```

**Comment by ffsantos92** [comment]
I have the same issue when i close the "Jekyll Manager" tab and change any file while server is running.

**Comment by aleksandar-todorovic** [comment]
I just installed the jekyll-atom package and tried to run the server from the directory that already contained some Jekyll code.

Got the same error.

**Comment by Arcath** [comment]
Version 1.0.0 does not have a console, and does not use this code any more. Hopefully it shouldn't happen again
