### ISSUE TITLE
Uncaught TypeError: Cannot read property 'kill' of null

### ISSUE THREAD

**Issue by fwartner** [Arcath/jekyll-atom#19]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.194.0
**System**: Mac OS X 10.10.3
**Thrown From**: [jekyll](https://github.com/arcath/jekyll-atom) package, v0.4.3

### Stack Trace

Uncaught TypeError: Cannot read property 'kill' of null

```
At /Users/fwartner/.atom/packages/jekyll/lib/server.coffee:73

TypeError: Cannot read property 'kill' of null
  at JekyllServer.module.exports.JekyllServer.stop (/Users/fwartner/.atom/packages/jekyll/lib/server.coffee:73:15)
  at /Users/fwartner/.atom/packages/jekyll/lib/server.coffee:15:45
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at ManagerView.module.exports.ManagerView.stopServer (/Users/fwartner/.atom/packages/jekyll/lib/manage-view.coffee:89:14)
  at HTMLButtonElement.<anonymous> (/Users/fwartner/.atom/packages/linter/node_modules/space-pen/lib/space-pen.js:214:36)
  at HTMLButtonElement.jQuery.event.dispatch (/Users/fwartner/.atom/packages/linter/node_modules/space-pen/vendor/jquery.js:4676:9)
  at HTMLButtonElement.elemData.handle (/Users/fwartner/.atom/packages/linter/node_modules/space-pen/vendor/jquery.js:4360:46)

```

### Commands

```
     -3:33 core:backspace (atom-text-editor.editor)
     -3:32.5.0 core:save (atom-text-editor.editor)
     -3:29.9.0 core:backspace (atom-text-editor.editor)
     -3:29.5.0 core:save (atom-text-editor.editor)
     -3:27.6.0 core:backspace (atom-text-editor.editor)
     -3:26.9.0 core:save (atom-text-editor.editor)
     -3:25.1.0 core:backspace (atom-text-editor.editor)
     -3:24.7.0 core:save (atom-text-editor.editor)
     -2:11.6.0 core:backspace (atom-text-editor.editor.mini)
     -2:10.9.0 core:confirm (atom-text-editor.editor.mini)
     -1:13.6.0 jekyll-new-post:new-post (button.btn.icon.enablement.icon-playback-pause)
     -1:07.3.0 core:confirm (atom-text-editor.editor.mini)
     -0:44.7.0 jekyll:new-post (atom-text-editor.editor)
     -0:37 editor:consolidate-selections (atom-text-editor.editor.mini)
     -0:37 core:cancel (atom-text-editor.editor.mini)
     -0:18 jekyll:toolbar (atom-text-editor.editor)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ],
    "disabledPackages": [
      "jekyll-new-post"
    ]
  }
}
```

### Installed Packages

```coffee
# User
autocomplete-plus, v2.12.0
color-picker, v1.7.0
emmet-atom, v2.3.8
jekyll, v0.4.3
linter, v0.12.0
minimap, v4.7.6

# Dev
No dev packages
```

**Comment by MrLoh** [comment]
For me the problem occurs when atom was killed. jekyll is still running, but somehow not available to kill via atom anymore. Only way to get it killed is to restart.
