### ISSUE TITLE
Uncaught TypeError: undefined is not a function

### ISSUE THREAD

**Issue by habibm** [Arcath/jekyll-atom#24]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.209.0
**System**: Mac OS X 10.10.3
**Thrown From**: [jekyll](https://github.com/arcath/jekyll-atom) package, v0.4.3

### Stack Trace

Uncaught TypeError: undefined is not a function

```
At /Users/habibashraf/.atom/packages/jekyll/lib/new-post-view.coffee:54

TypeError: undefined is not a function
  at JekyllNewPostView.module.exports.JekyllNewPostView.onConfirm (/Users/habibashraf/.atom/packages/jekyll/lib/new-post-view.coffee:54:33)
  at space-pen-div.atom.commands.add.core:confirm (/Users/habibashraf/.atom/packages/jekyll/lib/new-post-view.coffee:18:27)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:238:29)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:520:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:355:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:177:20)

```

### Commands

```
     -0:14.1.0 editor:checkout-head-revision (atom-text-editor.editor.is-focused)
     -0:09.8.0 zen:toggle (atom-text-editor.editor.is-focused)
  2x -0:09.8.0 tree-view:toggle (atom-workspace.workspace.scrollbars-visible-always.theme-atom-light-syntax.theme-atom-light-ui)
     -0:02.9.0 jekyll:new-post (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -0:00.5.0 core:confirm (atom-text-editor.editor.mini.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "language-scheme",
      "merge-conflicts"
    ],
    "themes": [
      "atom-light-ui",
      "atom-light-syntax"
    ]
  },
  "jekyll": {}
}
```

### Installed Packages

```coffee
# User
Zen, v0.14.0
jekyll, v0.4.3
language-csharp, v0.5.0

# Dev
No dev packages
```

**Comment by hrnn** [comment]
Hi @Arcath This is due to `atom.project.resolve` is deprecated and should be updated to  `atom.project.resolvePath`
I noticed that the current version in the main branch is 0.5 but `apm` still is installs `0.4.3`.

**Comment by pradyunsg** [comment]
Shouldn't it be 0.5.0?

**Comment by pradyunsg** [comment]
Still there on Atom 1.0.0 and jekyll-atom 1.0.0 (Ubuntu x64)

**Comment by adlermedrado** [comment]
Just got the same problem.

Steps to reproduce:

1. Packages -> Jekyll -> Open Data File

**Atom Version**: 1.0.5
**System**: Mac OS X 10.10.4
**Thrown From**: [jekyll](https://github.com/arcath/jekyll-atom) package, v1.0.0


### Stack Trace

Uncaught TypeError: undefined is not a function

```
At /Users/adler/.atom/packages/jekyll/lib/jekyll.coffee:107

TypeError: undefined is not a function
    at Object.module.exports.openData (/Users/adler/.atom/packages/jekyll/lib/jekyll.coffee:167:27)
    at atom-workspace.<anonymous> (/Users/adler/.atom/packages/jekyll/lib/jekyll.coffee:88:24)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:241:29)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:156:19)
    at EventEmitter.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:70:30)
    at emitOne (events.js:77:13)
    at EventEmitter.emit (events.js:166:7)
```

### Commands

```
     -0:01.4.0 jekyll:open-data (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
```

### Config

```json
{
  "core": {},
  "jekyll": {}
}
```

### Installed Packages

```coffee
# User
Sublime-Style-Column-Selection, v1.3.0
atom-pair, v2.0.4
atom-runner, v2.4.1
autocomplete-ctags, v0.3.1
autocomplete-php, v0.3.6
ctags-status, v1.3.3
git-diff-details, v0.20.0
jekyll, v1.0.0
linter, v1.3.2
linter-php, v1.0.3
linter-phpcs, v1.0.6
linter-phpmd, v1.0.0
php-getters-setters, v0.5.5

# Dev
No dev packages
```

**Comment by Arcath** [comment]
Is this still happening in 2.0.0?
