### ISSUE TITLE
Uncaught TypeError: Cannot read property 'open' of undefined

### ISSUE THREAD

**Issue by chrsmlls333** [Arcath/jekyll-atom#25]
[Enter steps to reproduce below:]

1. menu entry Jekyll > open config

**Atom Version**: 0.210.0
**System**: Microsoft Windows 8.1
**Thrown From**: [jekyll](https://github.com/arcath/jekyll-atom) package, v0.4.3

### Stack Trace

Uncaught TypeError: Cannot read property 'open' of undefined

```
At C:\Users\Christopher\.atom\packages\jekyll\lib\jekyll.coffee:99

TypeError: Cannot read property 'open' of undefined
  at Object.module.exports.openConfig (C:\Users\Christopher\.atom\packages\jekyll\lib\jekyll.coffee:99:23)
  at atom-workspace.<anonymous> (C:\Users\Christopher\.atom\packages\jekyll\lib\jekyll.coffee:43:67)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\Christopher\AppData\Local\atom\app-0.210.0\resources\app.asar\src\command-registry.js:238:29)
  at CommandRegistry.handleCommandEvent (C:\Users\Christopher\AppData\Local\atom\app-0.210.0\resources\app.asar\src\command-registry.js:3:61)
  at CommandRegistry.module.exports.CommandRegistry.dispatch (C:\Users\Christopher\AppData\Local\atom\app-0.210.0\resources\app.asar\src\command-registry.js:153:19)
  at EventEmitter.<anonymous> (C:\Users\Christopher\AppData\Local\atom\app-0.210.0\resources\app.asar\src\window-event-handler.js:70:30)
  at emitOne (events.js:77:13)
  at EventEmitter.emit (events.js:166:7)

```

### Commands

```
     -4:15.2.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -2:56.4.0 jekyll:toolbar (div.settings-view.pane-item)
  2x -2:51.1.0 deprecation-cop:view (atom-workspace.workspace.scrollbars-visible-always.theme-monokai.theme-one-dark-ui)
     -2:12.6.0 jekyll:manage (div.settings-view.pane-item)
     -0:03.6.0 jekyll:open-config (button.btn.btn-default.icon.icon-link-external)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "autoflow",
      "go-to-line",
      "wrap-guide"
    ],
    "themes": [
      "one-dark-ui",
      "monokai"
    ]
  }
}
```

### Installed Packages

```coffee
# User
browser-plus, v0.0.23
jekyll, v0.4.3
monokai, v0.14.0
processing-language, v0.1.0

# Dev
No dev packages
```

**Comment by Arcath** [comment]
Is this still happening in 1.0.0?
