### ISSUE TITLE
Error: spawn jekyll ENOENT

### ISSUE THREAD

**Issue by richardcopestake** [Arcath/jekyll-atom#36]
Can anyone help with this? 

 gulp
[17:33:31] Using gulpfile ~/projects/website/gulpfile.js
[17:33:31] Starting 'default'...
[17:33:31] Starting 'clean'...
[17:33:31] Finished 'clean' after 12 ms
[17:33:31] Starting 'lint'...
[17:33:31] Finished 'lint' after 287 ms
[17:33:31] Starting 'jekyll'...
[17:33:31] Starting 'scripts'...
[17:33:31] Starting 'libs'...
[17:33:31] Starting 'html'...
[17:33:31] Starting 'images'...
[17:33:31] Starting 'fonts'...
/Users/richard/projects/website/public/../node_modules/font-awesome/fonts/*
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: spawn jekyll ENOENT
    at exports._errnoException (util.js:837:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
    at onErrorNT (internal/child_process.js:344:16)
    at doNTCallback2 (node.js:429:9)
    at process._tickCallback (node.js:343:17)

**Comment by Arcath** [comment]
Is this using Gulp not Jekyll-Atom? might want to open an issue over there.
