### ISSUE TITLE
Uncaught YAMLException: duplicated mapping key at line 15, column 24:    gems: [jekyll-paginate]...

### ISSUE THREAD

**Issue by rahulpandita** [Arcath/jekyll-atom#48]
[Enter steps to reproduce below:]

1. Start Jekyll Server

**Atom Version**: 1.6.0
**System**: Mac OS X 10.11.3
**Thrown From**: [jekyll](https://github.com/arcath/jekyll-atom) package, v1.2.1

### Stack Trace

Uncaught YAMLException: duplicated mapping key at line 15, column 24:
    gems: [jekyll-paginate]
                           ^

```
At /Users/adminuser/.atom/packages/jekyll/node_modules/js-yaml/lib/js-yaml/loader.js:168

YAMLException: duplicated mapping key at line 15, column 24:
    gems: [jekyll-paginate]
                           ^
    at generateError (/Users/adminuser/.atom/packages/jekyll/node_modules/js-yaml/lib/js-yaml/loader.js:162:10)
    at throwError (/Users/adminuser/.atom/packages/jekyll/node_modules/js-yaml/lib/js-yaml/loader.js:168:9)
    at storeMappingPair (/Users/adminuser/.atom/packages/jekyll/node_modules/js-yaml/lib/js-yaml/loader.js:305:7)
    at readBlockMapping (/Users/adminuser/.atom/packages/jekyll/node_modules/js-yaml/lib/js-yaml/loader.js:1065:9)
    at composeNode (/Users/adminuser/.atom/packages/jekyll/node_modules/js-yaml/lib/js-yaml/loader.js:1326:12)
    at readDocument (/Users/adminuser/.atom/packages/jekyll/node_modules/js-yaml/lib/js-yaml/loader.js:1488:3)
    at loadDocuments (/Users/adminuser/.atom/packages/jekyll/node_modules/js-yaml/lib/js-yaml/loader.js:1544:5)
    at load (/Users/adminuser/.atom/packages/jekyll/node_modules/js-yaml/lib/js-yaml/loader.js:1561:19)
    at Object.safeLoad (/Users/adminuser/.atom/packages/jekyll/node_modules/js-yaml/lib/js-yaml/loader.js:1579:10)
    at Object.module.exports.handleConfigFileOpen (/Users/adminuser/.atom/packages/jekyll/lib/jekyll/utils.coffee:25:40)
    at /Users/adminuser/.atom/packages/jekyll/lib/jekyll/utils.coffee:20:21
    at FSReqWrap.oncomplete (fs.js:82:15)
```

### Commands

```
     -0:58.3.0 application:add-project-folder (ul.list-inline.tab-bar.inset-panel)
     -0:00.9.0 jekyll:toggle-server (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
```

### Config

```json
{
  "core": {
    "themes": [
      "one-light-ui",
      "one-light-syntax"
    ]
  },
  "jekyll": {
    "buildCommand": [
      "/usr/local/bin/jekyll",
      "build"
    ],
    "draftByDefault": true,
    "serverPort": 4000
  }
}
```

### Installed Packages

```coffee
# User
jekyll, v1.2.1
language-liquid, v0.4.0

# Dev
No dev packages
```

**Comment by Arcath** [comment]
Could you post your `_config.yml` please. Seems that Jekyll-Atom had some issues parsing it.

**Comment by rahulpandita** [comment]
# Site settings
title: Draft Workshop
#email: rxxx@gmail.com
#description: > # this means to ignore newlines until "baseurl:"
#  My outlook
baseurl: "/blog" # the subpath of your site, e.g. /blog/
url: "http://rxxx.me/" # the base hostname & protocol for your site
twitter_username: rxx_xx
github_username:  rxxx

# Build settings
markdown: kramdown

gems: [jemoji]
gems: [jekyll-paginate]

#pagination
paginate: 4

**Comment by Arcath** [comment]
You have 2 `gems` arrays which will be causing the yaml parser to explode.

Try

```yaml
gems:
  - jemoji
  - jekyll-paginate
```

Let me know how it goes.

**Comment by rahulpandita** [comment]
Works thanks!

On Thu, Mar 31, 2016 at 3:40 AM, Adam Laycock <notifications@github.com>
wrote:

> You have 2 gems arrays which will be causing the yaml parser to explode.
>
> Try
>
> gems:
>   - jemoji
>   - jekyll-paginate
>
> Let me know how it goes.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/Arcath/jekyll-atom/issues/48#issuecomment-203801199>
>



-- 
regards,
Rahul Pandita, PhD
Post Doctoral Researcher,
Department of Computer Science,
North Carolina State University

http://www.rahulpandita.me/
