### ISSUE TITLE
Uncaught ReferenceError: sdir is not defined

### ISSUE THREAD

**Issue by ibroadfo** [Arcath/jekyll-atom#49]
[Enter steps to reproduce below:]

1. trigger 'create new post'
2. check '_drafts'
3. profit

**Atom Version**: 1.6.2
**System**: Mac OS X 10.11.4
**Thrown From**: [jekyll](https://github.com/arcath/jekyll-atom) package, v1.4.0

### Stack Trace

Uncaught ReferenceError: sdir is not defined

```
At /Users/ibroadfo/.atom/packages/jekyll/lib/jekyll/new-post-view.coffee:40

ReferenceError: sdir is not defined
    at HTMLInputElement.<anonymous> (/Users/ibroadfo/.atom/packages/jekyll/lib/jekyll/new-post-view.coffee:40:44)
    at HTMLInputElement.jQuery.event.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4435:9)
    at HTMLInputElement.elemData.handle (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4121:28)
```

### Commands

```
     -7:33.6.0 fuzzy-finder:toggle-file-finder (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-atom-dark-syntax.theme-atom-dark-ui)
     -7:31.8.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -7:31.7.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -7:30 command-palette:toggle (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-atom-dark-syntax.theme-atom-dark-ui)
  8x -7:26 core:move-down (atom-text-editor.editor.mini.is-focused)
 10x -7:23 core:move-up (atom-text-editor.editor.mini.is-focused)
  2x -7:20.1.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -7:18.7.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -7:18.7.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -0:08.9.0 jekyll:new-post (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-atom-dark-syntax.theme-atom-dark-ui)
```

### Config

```json
{
  "core": {
    "ignoredNames": [
      ".git",
      ".svn",
      ".DS_Store"
    ],
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-ember-author-kit, v0.6.6
atom-qunit-snippets, v1.1.0
atomatigit, v1.5.5
auto-indent, v0.5.0
color-picker, v2.1.1
cucumber, v0.5.0
ember-cli-helper, v0.9.0
ember-snippets, v1.4.0
feedback, v0.38.0
git-diff-details, v1.1.0
jekyll, v1.4.0
jshint, v1.8.5
lang-bolt, v2.1.0
language-diff, v0.4.0
language-elixir, v0.12.3
language-ember-htmlbars, v0.3.0
language-lua, v0.9.4
pigments, v0.26.0
tag, v0.3.0
travis-ci-status, v1.0.0

# Dev
No dev packages
```

**Comment by Arcath** [comment]
Does this still happen in 1.4.1?

**Comment by ibroadfo** [comment]
yes, the same error occurs

**Comment by 128keaton** [comment]
Same issue over here

**Comment by serbrech** [comment]
so any idea?
Where is this sdir supposed to be come from? 
https://github.com/Arcath/jekyll-atom/blob/0877d770aa6ef9751886b342cead38f88921272f/lib/jekyll/new-post-view.coffee#L40

**Comment by Arcath** [comment]
Its supposed to be un checking all the other checkboxes, sorry this got into a released version.
