### ISSUE TITLE
Uncaught ReferenceError: draft is not defined

### ISSUE THREAD

**Issue by mathasonet** [Arcath/jekyll-atom#51]
[Enter steps to reproduce below:]

1. Open Jekyll project folder
2. Attempt to create a new post

**Atom Version**: 1.7.1
**System**: Mac OS X 10.11.5
**Thrown From**: [jekyll](https://github.com/arcath/jekyll-atom) package, v1.4.0

### Stack Trace

Uncaught ReferenceError: draft is not defined

```
At /Users/Mathew/.atom/packages/jekyll/lib/jekyll/new-post-view.coffee:75

ReferenceError: draft is not defined
    at JekyllNewPostView.module.exports.JekyllNewPostView.onConfirm (/Users/Mathew/.atom/packages/jekyll/lib/jekyll/new-post-view.coffee:75:46)
    at HTMLButtonElement.<anonymous> (/Users/Mathew/.atom/packages/jekyll/lib/jekyll/new-post-view.coffee:31:35)
    at HTMLButtonElement.jQuery.event.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4435:9)
    at HTMLButtonElement.elemData.handle (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4121:28)
```

### Commands

```
     -3:13.3.0 core:save (atom-text-editor.editor.is-focused)
     -3:02.8.0 core:copy (atom-text-editor.editor.is-focused)
  2x -3:02.4.0 core:backspace (atom-text-editor.editor.is-focused)
     -3:00.8.0 core:save (atom-text-editor.editor.is-focused)
     -2:58.6.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -2:56.8.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -2:56.8.0 jekyll:new-post (atom-text-editor.editor)
  6x -2:53.5.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -2:37.2.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -2:37.2.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -1:49.9.0 command-palette:toggle (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -1:45.8.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -1:45.8.0 jekyll:open-layout (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -0:09.8.0 command-palette:toggle (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -0:07.1.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:07.1.0 jekyll:new-post (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "language-ruby-on-rails",
      "linter",
      "autocomplete-elixir",
      "RubyMotion",
      "RubyMotion"
    ],
    "ignoredNames": [
      ".DS_Store",
      "._*",
      ".git",
      "Thumbs.db"
    ]
  },
  "jekyll": {
    "buildCommand": [
      "/usr/local/bin/jekyll",
      "build"
    ],
    "serverPort": 4000
  }
}
```

### Installed Packages

```coffee
# User
autocomplete-motion, v2.1.0
autocomplete-swift, v1.0.2
browser-plus, v0.0.60
file-icons, v1.7.2
jekyll, v1.4.0
language-elixir, v0.12.3
language-liquid, v0.4.0
language-rubymotion, v1.1.0
language-swift, v0.4.0
linter-rubocop, v0.4.7
terminal-plus, v0.14.5

# Dev
No dev packages
```

**Comment by xunorus** [comment]
Same here. This problem appeared after upgrading in ubuntu 15.10.
The only user package I have installed is terminal-plus, v0.14.5
Atom -v 1.7.0

**Comment by mathasonet** [comment]
Well, the function on line 75 of new-post-view.coffee was passing two values but the function definition in utils.coffee only expected one. If I knew anything about CoffeeScript I would try to help. I removed the second argument in my downloaded package and was able to get new posts to work just fine. 😅

**Comment by xunorus** [comment]
thaanks! it worked

**Comment by Arcath** [comment]
I've been on holiday the past few days, will look at this asap. Looks like it got missed when I moved to allowing many post folders.

**Comment by Arcath** [comment]
Sorted, sorry about that.

**Comment by mathasonet** [comment]
Not a problem! (: I should have done a proper pull request but I'm still getting my feet wet with Git.
