### ISSUE TITLE
Uncaught YAMLException: unidentified alias "folio" at line 2, column 14:    title: *folio      ...

### ISSUE THREAD

**Issue by shsiangg** [Arcath/jekyll-atom#52]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.7.4
**System**: Mac OS X 10.11.5
**Thrown From**: [jekyll](https://github.com/arcath/jekyll-atom) package, v1.4.2
### Stack Trace

Uncaught YAMLException: unidentified alias "folio" at line 2, column 14:
    title: *folio
                 ^

```
At /Users/Stephen/.atom/packages/jekyll/node_modules/js-yaml/lib/js-yaml/loader.js:168

YAMLException: unidentified alias "folio" at line 2, column 14:
    title: *folio
                 ^
    at generateError (/Users/Stephen/.atom/packages/jekyll/node_modules/js-yaml/lib/js-yaml/loader.js:162:10)
    at throwError (/Users/Stephen/.atom/packages/jekyll/node_modules/js-yaml/lib/js-yaml/loader.js:168:9)
    at readAlias (/Users/Stephen/.atom/packages/jekyll/node_modules/js-yaml/lib/js-yaml/loader.js:1243:5)
    at composeNode (/Users/Stephen/.atom/packages/jekyll/node_modules/js-yaml/lib/js-yaml/loader.js:1335:20)
    at readBlockMapping (/Users/Stephen/.atom/packages/jekyll/node_modules/js-yaml/lib/js-yaml/loader.js:1056:11)
    at composeNode (/Users/Stephen/.atom/packages/jekyll/node_modules/js-yaml/lib/js-yaml/loader.js:1326:12)
    at readDocument (/Users/Stephen/.atom/packages/jekyll/node_modules/js-yaml/lib/js-yaml/loader.js:1488:3)
    at loadDocuments (/Users/Stephen/.atom/packages/jekyll/node_modules/js-yaml/lib/js-yaml/loader.js:1544:5)
    at load (/Users/Stephen/.atom/packages/jekyll/node_modules/js-yaml/lib/js-yaml/loader.js:1561:19)
    at Object.safeLoad (/Users/Stephen/.atom/packages/jekyll/node_modules/js-yaml/lib/js-yaml/loader.js:1579:10)
    at Object.module.exports.handleConfigFileOpen (/Users/Stephen/.atom/packages/jekyll/lib/jekyll/utils.coffee:25:40)
    at /Users/Stephen/.atom/packages/jekyll/lib/jekyll/utils.coffee:20:21
    at FSReqWrap.oncomplete (fs.js:82:15)
```
### Commands

```
     -0:05.6.0 application:open (atom-text-editor.editor.is-focused)
     -0:00.6.0 jekyll:toggle-server (atom-text-editor.editor.is-focused)
```
### Config

``` json
{}
```
### Installed Packages

``` coffee
# User
atom-webbrowser, v2.1.4
jekyll, v1.4.2

# Dev
No dev packages
```

**Comment by Arcath** [comment]
Can you post your `_config.yml` Sounds like you have 2 `folio` entries in it.
