### ISSUE TITLE
Uncaught YAMLException: duplicated mapping key at line 35, column 24:   

### ISSUE THREAD

**Issue by xunorus** [Arcath/jekyll-atom#55]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.8.0
**System**: Ubuntu 16.04
**Thrown From**: [jekyll](https://github.com/arcath/jekyll-atom) package, v1.4.2

### Stack Trace

Uncaught YAMLException: duplicated mapping key at line 35, column 24:
    baseurl: "xunoeslastic" # the subpath of your site, e.g ... 
                           ^

```
At /home/xunorus/.atom/packages/jekyll/node_modules/js-yaml/lib/js-yaml/loader.js:168

YAMLException: duplicated mapping key at line 35, column 24:
    baseurl: "xunoeslastic" # the subpath of your site, e.g ... 
                           ^
    at generateError (/home/xunorus/.atom/packages/jekyll/node_modules/js-yaml/lib/js-yaml/loader.js:162:10)
    at throwError (/home/xunorus/.atom/packages/jekyll/node_modules/js-yaml/lib/js-yaml/loader.js:168:9)
    at storeMappingPair (/home/xunorus/.atom/packages/jekyll/node_modules/js-yaml/lib/js-yaml/loader.js:305:7)
    at readBlockMapping (/home/xunorus/.atom/packages/jekyll/node_modules/js-yaml/lib/js-yaml/loader.js:1065:9)
    at composeNode (/home/xunorus/.atom/packages/jekyll/node_modules/js-yaml/lib/js-yaml/loader.js:1326:12)
    at readDocument (/home/xunorus/.atom/packages/jekyll/node_modules/js-yaml/lib/js-yaml/loader.js:1488:3)
    at loadDocuments (/home/xunorus/.atom/packages/jekyll/node_modules/js-yaml/lib/js-yaml/loader.js:1544:5)
    at load (/home/xunorus/.atom/packages/jekyll/node_modules/js-yaml/lib/js-yaml/loader.js:1561:19)
    at Object.safeLoad (/home/xunorus/.atom/packages/jekyll/node_modules/js-yaml/lib/js-yaml/loader.js:1579:10)
    at Object.module.exports.handleConfigFileOpen (/home/xunorus/.atom/packages/jekyll/lib/jekyll/utils.coffee:25:40)
    at /home/xunorus/.atom/packages/jekyll/lib/jekyll/utils.coffee:20:21
    at FSReqWrap.oncomplete (fs.js:82:15)
```

### Commands

```
     -0:02.0 jekyll:new-post (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "allowPendingPaneItems": false,
    "autoHideMenuBar": true
  }
}
```

### Installed Packages

```coffee
# User
jekyll, v1.4.2
terminal-plus, v0.14.5

# Dev
No dev packages
```

**Comment by Arcath** [comment]
It sounds like you have 2 `baseurl`s in your _config.yml

**Comment by xunorus** [comment]
yep, It was that! 
After editing my _config.yml and restarting atom It again runs nice.
Thanks!!
