### ISSUE TITLE
Uncaught YAMLException: duplicated mapping key at line 32, column 24:    show_social_icons: true...

### ISSUE THREAD

**Issue by trozware** [Arcath/jekyll-atom#56]
[Enter steps to reproduce below:]
1. Installed jekyll package in atom
2. opened a jekyll post file
3. selected Packages/Jekyll/Toggle Server menu item

**Atom Version**: 1.9.6
**System**: Mac OS X 10.11.6
**Thrown From**: [jekyll](https://github.com/arcath/jekyll-atom) package, v1.4.2
### Stack Trace

Uncaught YAMLException: duplicated mapping key at line 32, column 24:
    show_social_icons: true
                           ^

```
At /Users/sarah/.atom/packages/jekyll/node_modules/js-yaml/lib/js-yaml/loader.js:168

YAMLException: duplicated mapping key at line 32, column 24:
    show_social_icons: true
                           ^
    at generateError (/Users/sarah/.atom/packages/jekyll/node_modules/js-yaml/lib/js-yaml/loader.js:162:10)
    at throwError (/Users/sarah/.atom/packages/jekyll/node_modules/js-yaml/lib/js-yaml/loader.js:168:9)
    at storeMappingPair (/Users/sarah/.atom/packages/jekyll/node_modules/js-yaml/lib/js-yaml/loader.js:305:7)
    at readBlockMapping (/Users/sarah/.atom/packages/jekyll/node_modules/js-yaml/lib/js-yaml/loader.js:1065:9)
    at composeNode (/Users/sarah/.atom/packages/jekyll/node_modules/js-yaml/lib/js-yaml/loader.js:1326:12)
    at readDocument (/Users/sarah/.atom/packages/jekyll/node_modules/js-yaml/lib/js-yaml/loader.js:1488:3)
    at loadDocuments (/Users/sarah/.atom/packages/jekyll/node_modules/js-yaml/lib/js-yaml/loader.js:1544:5)
    at load (/Users/sarah/.atom/packages/jekyll/node_modules/js-yaml/lib/js-yaml/loader.js:1561:19)
    at Object.safeLoad (/Users/sarah/.atom/packages/jekyll/node_modules/js-yaml/lib/js-yaml/loader.js:1579:10)
    at Object.module.exports.handleConfigFileOpen (/Users/sarah/.atom/packages/jekyll/lib/jekyll/utils.coffee:25:40)
    at /Users/sarah/.atom/packages/jekyll/lib/jekyll/utils.coffee:20:21
    at FSReqWrap.oncomplete (fs.js:82:15)
```
### Commands

```
     -0:14.4.0 markdown-writer:manage-post-tags (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -0:00.0 jekyll:toggle-server (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {
    "ignoredNames": [
      ".hg",
      ".svn",
      ".DS_Store",
      "._*",
      "Thumbs.db"
    ],
    "themes": [
      "one-light-ui",
      "solarized-light-syntax"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
atom-beautify, v0.29.10 (inactive)
jekyll, v1.4.2 (active)
markdown-writer, v2.5.1 (inactive)
pigments, v0.31.2 (active)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.51.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.43.0 (inactive)
base16-tomorrow-dark-theme, v1.1.0 (inactive)
base16-tomorrow-light-theme, v1.1.1 (inactive)
one-dark-ui, v1.3.2 (inactive)
one-light-ui, v1.3.2 (active)
one-dark-syntax, v1.2.0 (inactive)
one-light-syntax, v1.2.0 (inactive)
solarized-dark-syntax, v1.0.2 (inactive)
solarized-light-syntax, v1.0.2 (active)
about, v1.5.2 (active)
archive-view, v0.61.1 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.11.1 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.0 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.0 (active)
bookmarks, v0.41.0 (active)
bracket-matcher, v0.82.1 (active)
command-palette, v0.38.0 (inactive)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.38.3 (active)
fuzzy-finder, v1.3.0 (active)
git-diff, v1.1.0 (active)
find-and-replace, v0.198.0 (inactive)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.1 (active)
image-view, v0.58.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.1 (inactive)
markdown-preview, v0.158.0 (active)
metrics, v0.53.1 (active)
notifications, v0.64.1 (active)
open-on-github, v1.2.0 (inactive)
package-generator, v1.0.0 (inactive)
settings-view, v0.238.0 (active)
snippets, v1.0.2 (active)
spell-check, v0.67.1 (active)
status-bar, v1.4.1 (active)
styleguide, v0.46.0 (active)
symbols-view, v0.113.0 (inactive)
tabs, v0.98.0 (active)
timecop, v0.33.1 (active)
tree-view, v0.208.0 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.34.0 (active)
whitespace, v0.32.2 (active)
wrap-guide, v0.38.1 (active)
language-c, v0.52.1 (active)
language-clojure, v0.21.0 (active)
language-coffee-script, v0.47.0 (active)
language-csharp, v0.12.1 (active)
language-css, v0.36.2 (active)
language-gfm, v0.86.0 (active)
language-git, v0.13.0 (active)
language-go, v0.42.0 (active)
language-html, v0.44.1 (active)
language-hyperlink, v0.16.0 (active)
language-java, v0.22.0 (active)
language-javascript, v0.119.0 (active)
language-json, v0.18.0 (active)
language-less, v0.29.3 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.35.0 (active)
language-php, v0.37.0 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.0 (active)
language-ruby, v0.68.5 (active)
language-ruby-on-rails, v0.25.0 (active)
language-sass, v0.52.0 (active)
language-shellscript, v0.22.3 (active)
language-source, v0.9.0 (active)
language-sql, v0.21.1 (active)
language-text, v0.7.1 (active)
language-todo, v0.28.0 (active)
language-toml, v0.18.0 (active)
language-xml, v0.34.8 (active)
language-yaml, v0.26.0 (active)

# Dev
No dev packages
```

**Comment by Arcath** [comment]
Sounds like you have `show_social_icons` more than once in your YAML.

Can you post your `_config.yml`?
