### ISSUE TITLE
Uncaught YAMLException: duplicated mapping key at line 22, column 1:    paginate: 5    ^

### ISSUE THREAD

**Issue by 1nterp** [Arcath/jekyll-atom#61]
[Enter steps to reproduce:]

1. Ctrl + Shift + P 
2. Type command 'new post' and enter
3. Tada

**Atom**: 1.14.0 x64
**Electron**: 1.3.13
**OS**: Ubuntu 16.04.1
**Thrown From**: [jekyll](https://github.com/arcath/jekyll-atom) package 1.4.3

### Stack Trace

Uncaught YAMLException: duplicated mapping key at line 22, column 1:
    paginate: 5
    ^

```
At /home/interp/.atom/packages/jekyll/node_modules/js-yaml/lib/js-yaml/loader.js:168

YAMLException: duplicated mapping key at line 22, column 1:
    paginate: 5
    ^
    at generateError (/packages/jekyll/node_modules/js-yaml/lib/js-yaml/loader.js:162:10)
    at throwError (/packages/jekyll/node_modules/js-yaml/lib/js-yaml/loader.js:168:9)
    at storeMappingPair (/packages/jekyll/node_modules/js-yaml/lib/js-yaml/loader.js:307:7)
    at readBlockMapping (/packages/jekyll/node_modules/js-yaml/lib/js-yaml/loader.js:1070:9)
    at composeNode (/packages/jekyll/node_modules/js-yaml/lib/js-yaml/loader.js:1331:12)
    at readDocument (/packages/jekyll/node_modules/js-yaml/lib/js-yaml/loader.js:1493:3)
    at loadDocuments (/packages/jekyll/node_modules/js-yaml/lib/js-yaml/loader.js:1549:5)
    at load (/packages/jekyll/node_modules/js-yaml/lib/js-yaml/loader.js:1566:19)
    at Object.safeLoad (/packages/jekyll/node_modules/js-yaml/lib/js-yaml/loader.js:1584:10)
    at Object.handleConfigFileOpen (/packages/jekyll/lib/jekyll/utils.coffee:27:40)
    at /packages/jekyll/lib/jekyll/utils.coffee:22:21
    at FSReqWrap.oncomplete (fs.js:123:15)
```

### Commands

```
     -0:21.1.0 command-palette:toggle (div.deprecation-cop.pane-item.native-key-bindings)
     -0:19.7.0 core:confirm (input.hidden-input)
     -0:19.4.0 jekyll:new-post (div.deprecation-cop.pane-item.native-key-bindings)
```

### Non-Core Packages

```
atom-beautify 0.29.17 
jekyll 1.4.3 
language-liquid 0.5.1 
language-markdown 0.19.1 
```

**Comment by Arcath** [comment]
This is normally a YAML error in your `_config.yml` file.

Could you post you `_config.yml`?
