### ISSUE TITLE
Uncaught YAMLException: duplicated mapping key at line 65, column -120:    exclude:    ^

### ISSUE THREAD

**Issue by cheese10yun** [Arcath/jekyll-atom#63]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.14.3 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.12.3
**Thrown From**: [jekyll](https://github.com/arcath/jekyll-atom) package 1.4.3

### Stack Trace

Uncaught YAMLException: duplicated mapping key at line 65, column -120:
    exclude:
    ^

```
At /Users/cheese/.atom/packages/jekyll/node_modules/js-yaml/lib/js-yaml/loader.js:168

YAMLException: duplicated mapping key at line 65, column -120:
    exclude:
    ^
    at generateError (/packages/jekyll/node_modules/js-yaml/lib/js-yaml/loader.js:162:10)
    at throwError (/packages/jekyll/node_modules/js-yaml/lib/js-yaml/loader.js:168:9)
    at storeMappingPair (/packages/jekyll/node_modules/js-yaml/lib/js-yaml/loader.js:307:7)
    at readBlockMapping (/packages/jekyll/node_modules/js-yaml/lib/js-yaml/loader.js:1070:9)
    at composeNode (/packages/jekyll/node_modules/js-yaml/lib/js-yaml/loader.js:1331:12)
    at readDocument (/packages/jekyll/node_modules/js-yaml/lib/js-yaml/loader.js:1493:3)
    at loadDocuments (/packages/jekyll/node_modules/js-yaml/lib/js-yaml/loader.js:1549:5)
    at load (/packages/jekyll/node_modules/js-yaml/lib/js-yaml/loader.js:1566:19)
    at Object.safeLoad (/packages/jekyll/node_modules/js-yaml/lib/js-yaml/loader.js:1584:10)
    at Object.handleConfigFileOpen (/packages/jekyll/lib/jekyll/utils.coffee:27:40)
    at /packages/jekyll/lib/jekyll/utils.coffee:22:21
    at FSReqWrap.oncomplete (fs.js:123:15)
```

### Commands

```
     -0:53.9.0 application:open (input.hidden-input)
     -0:31.3.0 core:close (input.hidden-input)
     -0:23.1.0 command-palette:toggle (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
  2x -0:17.9.0 core:backspace (input.hidden-input)
  2x -0:16 core:move-up (input.hidden-input)
     -0:14.5.0 core:move-down (input.hidden-input)
     -0:14.2.0 core:move-up (input.hidden-input)
  3x -0:13.9.0 core:move-down (input.hidden-input)
  2x -0:10.6.0 core:move-up (input.hidden-input)
     -0:09.6.0 core:confirm (input.hidden-input)
     -0:09.4.0 jekyll:toggle-server (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
```

### Non-Core Packages

```
atom-beautify 0.29.17 
dash 1.7.0 
emmet 2.4.3 
intellij-idea-keymap 0.2.3 
jekyll 1.4.3 
jekyll-snippets 0.3.2 
jekyll-syntax-highlighting 0.1.0 
language-liquid 0.5.1 
linter 1.11.23 
linter-erb 1.0.3 
markdown-format 2.5.1 
markdown-preview-enhanced 0.9.9 
markdown-preview-plus 2.4.3 
markdown-writer 2.6.4 
script 3.14.1 
tool-bar-markdown-writer 0.2.0 
```

**Comment by Arcath** [comment]
Sorry this took a while.

Version 1.4.4 has just been released with this in.

**Comment by cheese10yun** [comment]
Thank you for the answer.

Have a nice day
