### ISSUE TITLE
Uncaught Error: listen EADDRINUSE :::3000

### ISSUE THREAD

**Issue by sangwoomoon** [Arcath/jekyll-atom#69]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.22.0 x64
**Electron**: 1.6.15
**OS**: Mac OS X 10.12.6
**Thrown From**: [jekyll](https://github.com/arcath/jekyll-atom) package 2.1.0

### Stack Trace

Uncaught Error: listen EADDRINUSE :::3000

```
At events.js:160

Error: listen EADDRINUSE :::3000
    at Object.exports._errnoException (util.js:1022:11)
    at exports._exceptionWithHostPort (util.js:1045:20)
    at Server._listen2 (net.js:1262:14)
    at listen (net.js:1298:10)
    at Server.listen (net.js:1376:9)
    at StaticServer.start (/packages/jekyll/node_modules/static-server/server.js:108:58)
    at Object.start (/packages/jekyll/lib/server/server.coffee:28:13)
    at Object.toggle (/packages/jekyll/lib/server/server.coffee:12:8)
    at Object.toggleServer (/packages/jekyll/lib/jekyll/jekyll.coffee:63:12)
    at /packages/jekyll/lib/main.coffee:65:11
    at /packages/jekyll/lib/jekyll/utils.coffee:16:74
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at Object.handleConfigFileOpen (/packages/jekyll/lib/jekyll/utils.coffee:49:21)
    at /packages/jekyll/lib/jekyll/utils.coffee:22:21
    at FSReqWrap.oncomplete (fs.js:112:15)
```

### Commands

```
  2x -0:29.1.0 core:move-up (input.hidden-input)
     -0:24.4.0 application:add-project-folder (input.hidden-input)
     -0:12.8.0 jekyll:toggle-server (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.30.6 
autocomplete-python 1.10.3 
jekyll 2.1.0 
language-liquid 0.6.0 
markdown-writer 2.7.3 
```

**Comment by Arcath** [comment]
Port 3000 is in use by something else on your computer.

If you specify the port in the package settings you can change it to a port that isn't in use.
