### ISSUE TITLE
Uncaught TypeError: Cannot read property '48' of undefined

### ISSUE THREAD

**Issue by TheCryptoWriter** [Arcath/jekyll-atom#74]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.25.0 x64
**Electron**: 1.7.11
**OS**: Microsoft Windows 10 Home
**Thrown From**: [jekyll](https://github.com/arcath/jekyll-atom) package 2.1.0

### Stack Trace

Uncaught TypeError: Cannot read property '48' of undefined

```
At C:\Users\david\.atom\packages\jekyll\lib\jekyll\jekyll.coffee:40

TypeError: Cannot read property '48' of undefined
    at Object.openInclude (/packages/jekyll/lib/jekyll/jekyll.coffee:40:63)
    at /packages/jekyll/lib/main.coffee:65:11
    at /packages/jekyll/lib/jekyll/utils.coffee:16:74
    at Function.module.exports.Emitter.simpleDispatch (~/AppData/Local/atom/app-1.25.0/resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (~/AppData/Local/atom/app-1.25.0/resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at Object.handleConfigFileOpen (/packages/jekyll/lib/jekyll/utils.coffee:49:21)
    at /packages/jekyll/lib/jekyll/utils.coffee:22:21
    at FSReqWrap.oncomplete (fs.js:114:15)
```

### Commands

```
     -0:22 jekyll:open-include (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.32.2 
atom-python-run 0.9.6 
atom-ternjs 0.18.3 
autocomplete-python 1.10.5 
autocomplete-ruby 0.2.8 
busy-signal 1.4.3 
gitignore-snippets 0.2.5 
go-plus 5.8.2 
Hydrogen 2.3.0 
ide-python 0.9.2 
intentions 1.1.5 
jekyll 2.1.0 
jekyll-snippets 0.3.2 
jekyll-syntax-highlighting 0.1.0 
jQuery 1.2.6 
jquery-snippets 11.0.0 
language-liquid 0.6.0 
linter 2.2.0 
linter-ruby 1.2.6 
linter-ui-default 1.7.1 
markdown-writer 2.7.3 
npm 2.0.0 
npm-helper 0.8.9 
npm-install 4.0.4 
npm-plus 0.4.0 
platformio-ide-terminal 2.8.1 
python-debugger 0.2.0 
python-indent 1.1.5 
python-tools 0.6.9 
rails-snippets 2.18.0 
ruby-block 0.3.6 
```

**Comment by TheCryptoWriter** [comment]
I fixed it by editing jekyll's settings to point to my local jekyll.bat file, it looks like atom is missing the .bat but not sure....
